#!/bin/bash
# Run this to begin the simulation.

function simulate() {
    cd "$(dirname "$0")/BSP/Simulator/DataGeneration/"
    
    # Do a quick check for operating system.
    # Right now, the only linux shell that is supported is gnome-terminal,
    # since that's the default on Ubuntu.
    if [[ $(uname -a | grep Microsoft) ]]; then
        echo "Launching a new WSL shell..."
        # This line makes me sad
        cmd.exe /c start cmd.exe /c wsl.exe python3 simulate.py &
    else
        echo "Launching gnome-terminal..."
        gnome-terminal --working-directory="$(pwd)" --geometry=103x33 -- python3 simulate.py  
    fi
    
    cd "../../../"

    ./bps-simulator.out
}

simulate
