#!/bin/bash

# This file is used to streamline the build of the BPS.
# This now just looks for a few special arguments, and
# if it doesn't see any, it will instead just pass the
# arguments along to Make.

# Update the timestamp on the main.c file so that make
# will rebuild that without needing to rebuild everything.
touch $(find . -iname main.c)

# check for test arguments
if [ "$1" = "test" ]
then
    echo "Running test program '$2'. "
    make USER_DEFS:="-D$2"

    exit 0
fi

make "$@"
