# workflow for running quick, simple tests in the simulator. Runs on every push
name: Simple Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt -y update
    - name: Initialize submodules
      run: git submodule update --init --recursive
    - name: build
      run: make simulator
    # simple test for verifying testing infrastructure
    - name: footest 
      run: ./bps-simulator.out BSP/Simulator/Data/footest.json
      run: python3 Validation/verify_test.py footest > footest.result
      run: diff footest.result Validation/Test_Results/footest.result
    # add more tests here