# workflow for running quick, simple tests in the simulator. Runs on every push
name: Simple Tests

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt -y update
        sudo apt -y install gcc-arm-none-eabi
    - name: Initialize submodules
      run: git submodule update --init --recursive
    - name: clean
      run: make clean
    - name: make simulator
      run: make simulator
    # simple test for verifying testing infrastructure
    # run tests in sudo for rtprio to work
    - name: Unit Test 
      run: |
        sudo bash Validation/test.sh critical_overcurrent.json
        sudo bash Validation/test.sh critical_overtemp_discharging.json
        sudo bash Validation/test.sh critical_overvolt.json
        sudo bash Validation/test.sh critical_undervolt.json
        sudo bash Validation/test.sh overcurrent.json
        sudo bash Validation/test.sh overtemp_charging.json
        sudo bash Validation/test.sh overtemp_discharging.json
        sudo bash Validation/test.sh overvolt.json
        sudo bash Validation/test.sh undervolt.json
        sudo bash Validation/test.sh killswitch.json
        echo -e "End of Manual Tests \n\n"
        sudo bash Validation/automatedTest.sh
    # add more tests here
