# workflow for running quick, simple tests in the simulator. Runs on every push
name: Simple Tests

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt -y update
        sudo apt -y install gcc-arm-none-eabi
    - name: Initialize submodules
      run: git submodule update --init --recursive
    - name: clean
      run: make clean
    - name: make simulator
      run: make simulator
    # simple test for verifying testing infrastructure
    # run tests in sudo for rtprio to work
    - name: Unit Test 
      run: |
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/critical_overcurrent.json
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/critical_overtemp_discharging.json
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/critical_overvolt.json
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/critical_undervolt.json
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/overcurrent.json
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/overtemp_charging.json
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/overtemp_discharging.json
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/overvolt.json
        sudo python3 Validation/verify_test.py BSP/Simulator/Data/ManualTests/undervolt.json
        ./Automatic_Tester.out a
    # add more tests here