name: Verify Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt -y update
        sudo apt -y install gcc-arm-none-eabi
    - name: Initialize submodules
      run: git submodule update --init --recursive
    - name: make stm32f413
      run: make stm32f413
    - name: clean
      run: make clean
    - name: make simulator
      run: make simulator
    - name: build CANbus
      run: rm ./bps-simulator.out && make simulator TEST=CI_CANbus && mkdir BSP/Simulator/DataGeneration/Data
    - name: run CANbus
      run: sudo ./Continuous_Integration/CANbus/Test_CANbus.sh
